name: Keep Railway Night Time

on:
  schedule:
    - cron: "*/5 16 * * *"     # 23:00-23:59 VN
    - cron: "*/5 17-23 * * *"  # 00:00-06:00 VN
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Railway
        run: |
          curl -I https://excel2wordproject-production.up.railway.app
