name: Keep Render Awake (Night Only)

on:
  schedule:
    - cron: "*/5 23 * * *"     # 06:00 - 06:59 VN (23 UTC)
    - cron: "*/5 0-16 * * *"   # 07:00 - 23:00 VN (0-16 UTC)
  workflow_dispatch:            # cho chạy thủ công lúc cần

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App (GET request)
        run: |
          curl -L -s -o /dev/null -w "%{http_code}" https://excel2word-project-1.onrender.com
